# Generated by Django 3.0.5 on 2020-11-06 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_order', models.IntegerField(default=50, verbose_name='Page order')),
                ('product', models.CharField(max_length=30, verbose_name='Product')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('price_tax', models.IntegerField(verbose_name='Price tax')),
                ('shipping', models.BooleanField(default=False, verbose_name='Shipping')),
                ('shipping_price', models.IntegerField(default=0, verbose_name='Shipping cost')),
                ('shipping_tax', models.IntegerField(verbose_name='Price tax')),
                ('available', models.BooleanField(default=False, verbose_name='Available')),
                ('coming_soon', models.BooleanField(default=False, verbose_name='Coming soon')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-available', 'product'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, max_length=300, null=True, verbose_name='Message')),
                ('GDPR', models.BooleanField(default=True, verbose_name='Allow communication')),
                ('order_delivered', models.BooleanField(default=False, verbose_name='Was order completed')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timelapse.Product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('order_delivered', 'timestamp'),
            },
        ),
    ]
