# Generated by Django 3.0.5 on 2020-11-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse', '0002_auto_20201106_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_tax',
            field=models.IntegerField(verbose_name='Shipping tax'),
        ),
    ]
