# Generated by Django 3.0.5 on 2020-11-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse', '0003_auto_20201106_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_stripe',
            field=models.CharField(default='', max_length=30, verbose_name='Price_ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_tax_stripe',
            field=models.CharField(default='', max_length=30, verbose_name='Price_tax_ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_price_stripe',
            field=models.CharField(default='', max_length=30, verbose_name='Shipping_price_ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_tax_stripe',
            field=models.CharField(default='', max_length=30, verbose_name='Shipping_tax_ID'),
        ),
    ]
