# Generated by Django 3.0.5 on 2020-11-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse', '0004_auto_20201106_0142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
