# Generated by Django 3.0.5 on 2020-11-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse', '0007_auto_20201107_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Shipping cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_price_stripe',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Shipping_price_ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_tax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Shipping tax'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_tax_stripe',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Shipping_tax_ID'),
        ),
    ]
