# Generated by Django 3.1 on 2020-08-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('order_delivered', 'timestamp'), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Message'),
        ),
    ]
