# Generated by Django 3.1 on 2020-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse', '0002_auto_20200824_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='coming_soon',
            field=models.BooleanField(default=False, verbose_name='Coming soon'),
        ),
    ]
