# Generated by Django 3.1 on 2020-08-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse', '0005_service_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='page_order',
            field=models.IntegerField(default=50, verbose_name='Page order'),
        ),
    ]
