# Generated by Django 3.1 on 2020-08-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse', '0007_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=30, verbose_name='Product'),
        ),
    ]
