# Generated by Django 3.1 on 2020-08-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse', '0008_auto_20200827_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-available', 'product'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='service',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='service',
            new_name='product',
        ),
    ]
